# Generated by Django 5.0.1 on 2024-01-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('product_category', models.CharField(max_length=100, verbose_name='Product Category')),
                ('purchased_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Seller', models.CharField(max_length=100)),
            ],
        ),
    ]
