# Generated by Django 5.0.1 on 2024-01-13 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_assign_alter_category_options_product_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.product'),
            preserve_default=False,
        ),
    ]
