# Generated by Django 5.0.1 on 2024-02-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_alter_category_options_rename_seller_product_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='category',
        ),
    ]
