# Generated by Django 5.0.1 on 2024-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_assign_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='staff_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
