# Generated by Django 5.0.1 on 2024-01-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_department_staff_name_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='assigned_for',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='assigned',
        ),
    ]
