# Generated by Django 5.0.1 on 2024-01-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_remove_assign_assigned_for_remove_assign_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='staff_name',
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.department')),
            ],
        ),
    ]
