# Generated by Django 5.0.1 on 2024-01-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_remove_department_staff_name_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
