# Generated by Django 5.0.1 on 2024-01-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_assign_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.employee'),
            preserve_default=False,
        ),
    ]
