# Generated by Django 5.0.1 on 2024-01-13 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_assign_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.product'),
        ),
    ]
