# Generated by Django 5.0.1 on 2024-01-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0010_alter_assign_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Seller',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='product',
        ),
    ]
