# Generated by Django 5.0.1 on 2024-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0012_product_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assign',
        ),
        migrations.RemoveField(
            model_name='product',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='product',
            name='assigned_to',
            field=models.ManyToManyField(to='ims.employee'),
        ),
    ]
