# Generated by Django 5.0.1 on 2024-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0015_alter_product_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='product',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, to='ims.employee'),
        ),
    ]
