# Generated by Django 5.0.1 on 2024-01-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0016_remove_product_assigned_to_product_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='ims.employee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
