# Generated by Django 5.0.1 on 2024-01-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0019_remove_product_assigned_to_product_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='Asign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('pro_id', models.PositiveIntegerField(verbose_name='Product Id')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.product')),
            ],
        ),
    ]
