# Generated by Django 5.0.1 on 2024-01-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0020_remove_product_assigned_to_asign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('pro_id', models.PositiveIntegerField(verbose_name='Product Id')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Asign',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
