# Generated by Django 5.0.1 on 2024-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0021_remove_employee_department_remove_product_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
