# Generated by Django 5.0.1 on 2024-01-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0023_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ims.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.category'),
        ),
    ]
