# Generated by Django 5.0.1 on 2024-01-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0025_assign_qr_code_alter_assign_pro_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.category'),
            preserve_default=False,
        ),
    ]
